/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.demo.avro;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UserSessionsKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserSessionsKey\",\"namespace\":\"com.demo.avro\",\"fields\":[{\"name\":\"anonymous_id\",\"type\":\"int\"}]}");
    private static final long serialVersionUID = -7370906425824664406L;
    private static SpecificData MODEL$ = new SpecificData();
    private static final BinaryMessageEncoder<UserSessionsKey> ENCODER =
            new BinaryMessageEncoder<UserSessionsKey>(MODEL$, SCHEMA$);
    private static final BinaryMessageDecoder<UserSessionsKey> DECODER =
            new BinaryMessageDecoder<UserSessionsKey>(MODEL$, SCHEMA$);
    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<UserSessionsKey>
            WRITER$ = (org.apache.avro.io.DatumWriter<UserSessionsKey>) MODEL$.createDatumWriter(SCHEMA$);
    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<UserSessionsKey>
            READER$ = (org.apache.avro.io.DatumReader<UserSessionsKey>) MODEL$.createDatumReader(SCHEMA$);
    private int anonymous_id;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public UserSessionsKey() {
    }

    /**
     * All-args constructor.
     * @param anonymous_id The new value for anonymous_id
     */
    public UserSessionsKey(java.lang.Integer anonymous_id) {
        this.anonymous_id = anonymous_id;
    }

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     */
    public static BinaryMessageDecoder<UserSessionsKey> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     */
    public static BinaryMessageDecoder<UserSessionsKey> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<UserSessionsKey>(MODEL$, SCHEMA$, resolver);
    }

    /** Deserializes a UserSessionsKey from a ByteBuffer. */
    public static UserSessionsKey fromByteBuffer(
            java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    /**
     * Creates a new UserSessionsKey RecordBuilder.
     * @return A new UserSessionsKey RecordBuilder
     */
    public static com.demo.avro.UserSessionsKey.Builder newBuilder() {
        return new com.demo.avro.UserSessionsKey.Builder();
    }

    /**
     * Creates a new UserSessionsKey RecordBuilder by copying an existing Builder.
     * @param other The existing builder to copy.
     * @return A new UserSessionsKey RecordBuilder
     */
    public static com.demo.avro.UserSessionsKey.Builder newBuilder(com.demo.avro.UserSessionsKey.Builder other) {
        return new com.demo.avro.UserSessionsKey.Builder(other);
    }

    /**
     * Creates a new UserSessionsKey RecordBuilder by copying an existing UserSessionsKey instance.
     * @param other The existing instance to copy.
     * @return A new UserSessionsKey RecordBuilder
     */
    public static com.demo.avro.UserSessionsKey.Builder newBuilder(com.demo.avro.UserSessionsKey other) {
        return new com.demo.avro.UserSessionsKey.Builder(other);
    }

    /** Serializes this UserSessionsKey to a ByteBuffer. */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return anonymous_id;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                anonymous_id = (java.lang.Integer) value$;
                break;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    /**
     * Gets the value of the 'anonymous_id' field.
     * @return The value of the 'anonymous_id' field.
     */
    public java.lang.Integer getAnonymousId() {
        return anonymous_id;
    }

    /**
     * Sets the value of the 'anonymous_id' field.
     * @param value the value to set.
     */
    public void setAnonymousId(java.lang.Integer value) {
        this.anonymous_id = value;
    }

    @Override
    public void writeExternal(java.io.ObjectOutput out)
            throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @Override
    public void readExternal(java.io.ObjectInput in)
            throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    /**
     * RecordBuilder for UserSessionsKey instances.
     */
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserSessionsKey>
            implements org.apache.avro.data.RecordBuilder<UserSessionsKey> {

        private int anonymous_id;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         * @param other The existing Builder to copy.
         */
        private Builder(com.demo.avro.UserSessionsKey.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.anonymous_id)) {
                this.anonymous_id = data().deepCopy(fields()[0].schema(), other.anonymous_id);
                fieldSetFlags()[0] = true;
            }
        }

        /**
         * Creates a Builder by copying an existing UserSessionsKey instance
         * @param other The existing instance to copy.
         */
        private Builder(com.demo.avro.UserSessionsKey other) {
            super(SCHEMA$);
            if (isValidValue(fields()[0], other.anonymous_id)) {
                this.anonymous_id = data().deepCopy(fields()[0].schema(), other.anonymous_id);
                fieldSetFlags()[0] = true;
            }
        }

        /**
         * Gets the value of the 'anonymous_id' field.
         * @return The value.
         */
        public java.lang.Integer getAnonymousId() {
            return anonymous_id;
        }

        /**
         * Sets the value of the 'anonymous_id' field.
         * @param value The value of 'anonymous_id'.
         * @return This builder.
         */
        public com.demo.avro.UserSessionsKey.Builder setAnonymousId(int value) {
            validate(fields()[0], value);
            this.anonymous_id = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'anonymous_id' field has been set.
         * @return True if the 'anonymous_id' field has been set, false otherwise.
         */
        public boolean hasAnonymousId() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'anonymous_id' field.
         * @return This builder.
         */
        public com.demo.avro.UserSessionsKey.Builder clearAnonymousId() {
            fieldSetFlags()[0] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public UserSessionsKey build() {
            try {
                UserSessionsKey record = new UserSessionsKey();
                record.anonymous_id = fieldSetFlags()[0] ? this.anonymous_id : (java.lang.Integer) defaultValue(fields()[0]);
                return record;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

}
